# This is a basic workflow to help you get started with Actions

name: cd-synapse
# Controls when the workflow will run
on:
  workflow_dispatch:
#Run only when the pull request is closed and it targets main branch
  # push:
    
  #   branches:
  #   - main
  #   paths-ignore:
  #     - '.github/**'
  #     - 'build/**'
  #     - 'README.md'
  #     - 'CODEOWNERS'

# Modify the default permissions granted to GITHUB_TOKEN.
permissions:
      id-token: write
      contents: write
      packages: write

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout local
        uses: actions/checkout@v3
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
      - name: Synapse workspace deployment
        uses: Azure/Synapse-workspace-deployment@V1.8.0
        with:
          TargetWorkspaceName: 'ws-synapse-tm'
          TemplateFile: './ws-synapse-tm/TemplateForWorkspace.json'
          ParametersFile: './ws-synapse-tm/TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: 'DNA_Reporting'
          # clientId: ${{ secrets.CLIENT_ID }}
          managedIdentity: true
          # clientSecret: ${{ secrets.CLIENT_SECRET }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          DeleteArtifactsNotInTemplate: 'true'
          operation: 'deploy'
